/*
 * File: product/model/Product.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Product.model.Product', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'productUuid'
        },
        {
            name: 'productName'
        },
        {
            name: 'productNum'
        },
        {
            name: 'productSpecifications'
        },
        {
            name: 'productBzPrice'
        },
        {
            name: 'productPgPrice'
        },
        {
            name: 'productZgPrice'
        },
        {
            name: 'productWeight'
        },
        {
        	name: 'productState'
        },
        {
        	name: 'productStateText'
        },
        {
            name: 'deleteType'
        },
        {
            name: 'productOrderBy'
        },
        {
            name: 'productNote'
        },
        {
            name: 'createTime'
        },
        {
        	name:'productYeild'
        }
    ]
});