/*
 * File: resigned/store/ResignedStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Resigned.store.ResignedStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Resigned.model.Resigned'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Resigned.model.Resigned',
            storeId: 'ResignedStore',
            autoLoad:false,
            proxy: {
                type: 'ajax',
                url: 'resigned/getResignedPage.do',
                extraParams: {"resState":DIC_RESIGNED_STATE_NO,"userBankCard":DIC_BANK_CARD_STATE_NO},
                reader: {
		        	type: 'json',
		   	  	 	//数据格式为json   
		            root: 'data',
		            //获取数据总数 
		            totalProperty:'dataSize'
                }
            }
        }, cfg)]);
    }
});