/*
 * File: mainFrame/view/UserAuthorityInfoWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mainFrame.view.UserAuthorityInfoWindow', {
    extend: 'Ext.window.Window',

    height: 300,
    id: 'UserAuthorityInfoWindow',
    width: 423,
    layout: {
        type: 'border'
    },
    title: '申请授权详细信息',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'center',
                    margin: 2,
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            region: 'center',
                            frame: true,
                            id: 'UserAuthorityForm',
                            margin: '0 0 2 0',
                            bodyPadding: 10,
                            header: false,
                            title: '申请授权表单',
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: '主键Uuid',
                                    readOnly: true,
                                    name: 'uuid'
                                },
                                    
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '申请人',
                                    readOnly: true,
                                    name: 'userName'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '申请时间',
                                    readOnly: true,
                                    name: 'createTime'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: '状态',
                                    name: 'state',
                                    displayField: 'text',
                                    valueField: 'id',
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    editable: false,//启用编辑，主要是为了清空当前的选择项
                                    store:'ChangeUserStateStore',
                                    listeners:{
                                      	afterrender:function(combol){
                                			var index=combol.store.find('text',combol.value);
                                      	}
                                	}
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 116,
                                    fieldLabel: '申请说明',
                                    readOnly: true,
                                    name: 'note'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            region: 'south',
                            //height: 40,
                            items: [
                                '->',
                                {
                                    xtype: 'button',
                                    id: 'User_authority_info_save_btn',
                                    icon: 'img/save.png',
                                    text: '保存'
                                },
                                {
                                	xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    id: 'User_authority_info_close_btn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});