/*
 * File: mainFrame/view/UserAuthorityNoteWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mainFrame.view.UserAuthorityNoteWindow', {
    extend: 'Ext.window.Window',

    height: 247,
    id: 'UserAuthorityNoteWindow',
    width: 437,
    layout: {
        type: 'fit'
    },
    title: '申请说明',
    maximizable: true,
    modal: true,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    margin: 2,
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'south',
                           // height: 40,
                            margin: '2 0 0 0 ',
                            items: [
                                '->',
                                {
                                    xtype: 'button',
                                    id: 'User_authority_save_btn',
                                    icon: 'img/save.png',
                                    text: '保存'
                                },
                                {
                                	xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    icon: 'img/close.png',
                                    id:'User_authority_close_btn',
                                    text: '关闭'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'center',
                            frame: true,
                            bodyPadding: 10,
                            header: false,
                            title: '申请说明表单',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 137,
                                    id: 'UserAuthorityNote',
                                    fieldLabel: ''
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});