/*
 * File: power/view/PowerOperateWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Power.view.PowerOperateWindow', {
    extend: 'Ext.window.Window',

    height: 530,
    width: 725,
    layout: {
        type: 'fit'
    },
    title: '功能权限',
    maximizable: true,
    modal: true,
    id:'PowerOperateWindow',
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'north',
                            //height: 40,
                            margin: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'Operate_refresh_btn',
                                    icon: 'img/reload.png',
                                    hidden:exists('Power_reset_btn'),
                                    text: '刷新'
                                },
                                {
                                	xtype: 'tbseparator',
                                	hidden:exists('Power_reset_btn')
                                },
                                {
                                    xtype: 'button',
                                    id: 'Operate_add_btn',
                                    icon: 'img/add.png',
                                    hidden:exists('Operate_add_btn'),
                                    text: '添加'
                                },
                                {
                                	xtype: 'tbseparator',
                                	hidden:exists('Operate_add_btn')
                                },
                                {
                                    xtype: 'button',
                                    id: 'Operate_upd_btn',
                                    icon: 'img/update.png',
                                    disabled:true,
                                    hidden:exists('Operate_upd_btn'),
                                    text: '修改'
                                },
                                {
                                	xtype: 'tbseparator',
                                	hidden:exists('Operate_upd_btn')
                                },
                                {
                                    xtype: 'button',
                                    id: 'Operate_del_btn',
                                    icon: 'img/del.png',
                                    disabled:true,
                                    hidden:exists('Operate_del_btn'),
                                    text: '删除'
                                },
                                {
                                	xtype: 'tbseparator',
                                	 hidden:exists('Operate_del_btn')
                                },
                                {
                                    xtype: 'button',
                                    id: 'Operate_close_gridPanel_btn',
                                    icon: 'img/close.png',
                                    hidden:exists('Operate_close_gridPanel_btn'),
                                    text: '关闭'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'operateGridPanel',
                            margin: '0 2 2 2',
                            title: '操作功能管理',
                            store: 'OperateGridPanelStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 39,
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operateKey',
                                    text: '标识'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operateName',
                                    text: '名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operateIcon',
                                    text: '图标',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                                		if(null!=data){
                                			return '<img src=\''+data+"\''/>"
                                		}else{
                                			return data;
                                		}
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operateNote',
                                    text: '说明'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operateOrderBy',
                                    text: '排序'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'createTime',
                                    text: '创建时间'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'OperateGridPanelStore'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});