/*
 * File: logs/controller/LogsController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Logs.controller.LogsController', {
    extend: 'Ext.app.Controller',

    id: 'LogsController',
    models: [
        'LogsModel'
    ],
    stores: [
        'LogsStore'
    ],
    views: [
        'LogsViewport'
    ],

    //刷新按钮
    onLogs_refresh_btnClick: function(button, e, eOpts) {
		Ext.getCmp("LogGridPanel").store.load();
    },
    //LogGridPanel双击事件
    onLogGridPanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
    	Ext.create("Logs.view.LogsInfoWindow").show();
    	Ext.getCmp("LogsForm").getForm().loadRecord(record);
    },
    //关闭按钮
    onLogs_window_close_btnClick: function(button, e, eOpts) {
    	Ext.getCmp("LogsInfoWindow").close();
    },
    //查询按钮：重新加载gridpanle数据
    onLogs_search_btnClick: function(button, e, eOpts) {
    	this.reloadGridPanelStore();
    },
    //重置按钮
    onLogs_reset_btnClick: function(button, e, eOpts) {
    	Ext.getCmp("Logs_Search_Form").getForm().reset();
    	this.reloadGridPanelStore();
    },
    //重新加载gridpanle数据
    reloadGridPanelStore:function(){
    	var gridPanel = Ext.getCmp("LogGridPanel");
    	gridPanel.store.setProxy({
	    		 type: 'ajax', 
	    		 url: 'logs/getLogsList.do',
	    		 extraParams:Ext.getCmp("Logs_Search_Form").getForm().getValues(),
    		 	 reader: {
	    			 type: 'json',
	          	  	 //数据格式为json
	                 root: 'data',   
	                 //获取数据总数 
	                 totalProperty: 'dataSize'
    		 	}
		 }); 
    	gridPanel.store.load(); 
    },
    //删除按钮
    onLogs_del_btnClick: function(button, e, eOpts) {
    	var panel = Ext.getCmp("LogGridPanel");
        var selectionModel = panel.getSelectionModel();
        if(selectionModel.getCount()<=0){
            Ext.Msg.alert("提示信息","请先选中一条数据。");
            return;
        }
        var obj = selectionModel.getSelection()[0].data;
        Ext.MessageBox.confirm("提示信息", "确定要删除吗？", function (btnId) {
            if (btnId == "yes") {
            	Ext.Msg.wait('正在处理数据，请稍候...','提示');
            	Ext.Ajax.request({
            	    url: 'logs/delLogs.do',
            	    params: {
            			logUuid: obj.logUuid
            	    },
            	    method:'POST',
            	    success: function(response){
            	    	Ext.Msg.hide();
            	        var result = JSON.parse(response.responseText); 
            	        if(result.success){
            	        	  Ext.Msg.alert("提示信息","删除成功");
            	        	 this.onLogs_refresh_btnClick();
            	        }else{
            	        	  Ext.Msg.alert("提示信息","删除失败");
            	        }
            	    },
        		    failure: function(from,action){
            			 Ext.Msg.hide();
            			 onActionFailureTypeShow(action);
            		},
            	    scope:this
            	});
            }
        },this);
    },
    //重置按钮
    onLogs_show_search_btnClick: function(button, e, eOpts) {
    	  var panel = Ext.getCmp("Logs_Search_Form");
          if(panel.isHidden()){
              panel.show();
          }else{
              panel.hide();
          }
    },
    init: function(application) {
        this.control({
            "button[id=Logs_refresh_btn]": {
                click: this.onLogs_refresh_btnClick
            },
            "panel[id=LogGridPanel]":{
            	itemdblclick: this.onLogGridPanelItemDblClick
            },
            "button[id=Logs_window_close_btn]":{
            	click: this.onLogs_window_close_btnClick
            },
            "button[id=Logs_search_btn]":{
            	click: this.onLogs_search_btnClick
            },
            "button[id=Logs_reset_btn]":{
            	click: this.onLogs_reset_btnClick
            },
            "button[id=Logs_del_btn]":{
            	click: this.onLogs_del_btnClick
            },
            "button[id=Logs_show_search_btn]":{
            	click: this.onLogs_show_search_btnClick
            }
            
        });
    }

});
