/*
 * File: record/view/RecordWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Record.view.RecordWindow', {
    extend: 'Ext.window.Window',

    height: 334,
    id: 'RecordWindow',
    width: 363,
    layout: {
        type: 'fit'
    },
    title: '员工档案记录',
    modal:true,
    resizable: false,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            region: 'center',
                            frame: true,
                            margin: 2,
                            bodyPadding: 10,
                            header: false,
                            title: '员工档案表单',
                            id:'RecordFormPanel',
                            trackResetOnLoad:true,
                            items: [
								{
								    xtype: 'hiddenfield',
								    fieldLabel: '档案uuid',
								    id: 'recordUuid',
								    name: 'recordUuid'
								},
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: '记录日期',
                                    name: 'recordDate',
                                    value:new Date(),
                                    format:'Y-m-d',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'container',
                                    height: 24,
                                    margin: '3 0 3 0 ',
                                    layout: {
                                        type: 'column'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            width: 253,
                                            fieldLabel: '员工工号',
                                            name: 'recordUserNumber',
                                            id:'recordUserNumber',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'RecordChoseUserBtn',
                                            margin: '0 0 0 10',
                                            icon: 'img/search.png',
                                            text: '选择'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '员工号',
                                    id:'recordUserNumber_hidden'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '员工姓名',
                                    id: 'recordUserName',
                                    name: 'recordUserName'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '员工性别',
                                    id:'recordUserGender',
                                    name: 'recordUserGender'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: '员工uuid',
                                    id:'recordUserUuid',
                                    name: 'recordUserUuid'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: '档案类别',
                                    name: 'recordType',
                                    allowBlank: false,
                                    displayField: 'text',
                                    valueField: 'id',
                                    editable: false,//启用编辑，主要是为了清空当前的选择项
                                    store:'RecordTypeStore'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '档案名称',
                                    name: 'recordAttName',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'filefield',
                                    anchor: '100%',
                                    fieldLabel: '档案附件',
                                    name: 'file',
                                    buttonText: '浏览',
                                    //allowBlank: false,
                                    buttonConfig: {
                                        xtype: 'filebutton',
                                        icon: 'img/find.png',
                                        text: '浏览'
                                    }
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 113,
                                    fieldLabel: '档案说明',
                                    name: 'recordNote'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            region: 'south',
                            margin: '0 2 2 2',
                            items: [
                                '->',
                                {
                                    xtype: 'button',
                                    id: 'RecordSaveBtn',
                                    icon: 'img/save.png',
                                    text: '保存'
                                },
                                {
                                    xtype: 'button',
                                    id: 'RecordCloseBtn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});