/*
 * File: record/model/Record.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Record.model.Record', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'recordUuid'
        },
        {
            name: 'recordDate'
        },
        {
            name: 'recordUserUuid'
        },
        {
            name: 'recordUserNumber'
        },
        {
            name: 'recordUserName'
        },
        {
            name: 'recordUserGender'
        },
        {
            name: 'recordType'
        },
        {
            name: 'recordAttName'
        },
        {
            name: 'recordAttFileName'
        },
        {
        	name:'recordAttType'
        },
        {
            name: 'recordAttContent'
        },
        {
            name: 'recordAttLength'
        },
        {
            name: 'createTime'
        },
        {
            name: 'createUserUuid'
        },
        {
            name: 'createUserName'
        },
        {
            name: 'recordTypeText'
        },
        {
            name: 'recordUserGenderText'
        },
        {
        	name:'recordNote'
        }
    ]
});