/*
 * File: monthReport/view/LoggingDetailWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MonthReport.view.LoggingDetailWindow', {
    extend: 'Ext.window.Window',

    height: 449,
    id: 'LoggingDetailWindow',
    width: 600,
    layout: {
        type: 'fit'
    },
    title: '明细查询',
    maximizable: true,
    //maximized: true,
    modal: true,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    width: 150,
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'north',
                            margin: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'DetailReloadBtn',
                                    icon: 'img/reload.png',
                                    text: '刷新'
                                },
                                {
                                    xtype: 'button',
                                    id: 'DetailExportBtn',
                                    icon: 'img/excel.png',
                                    text: '导出'
                                },
                                {
                                    xtype: 'button',
                                    id: 'DetailCloseBtn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            margin: '0 2 2 2',
                            title: '工资明细查询',
                            id:'DetailGridPanel',
                            header:false,
                            store:'LoggingStore',
                            columns: [
                                 {
		                            xtype: 'rownumberer',
		                            width: 39,
		                            text: '序号'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingDate',
		                            text: '日期'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingUserName',
		                            text: '员工姓名'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingUserNumber',
		                            text: '员工号'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingUserSex',
		                            text: '性别',
		                            renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
		                        		return record.data.loggingUserSexText;
				                  	}
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingType',
		                            text: '工作性质',
		                            renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
		                        		return record.data.loggingTypeText;
				                  	}
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingWages',
		                            text: '日工资额',
		                            summaryType: 'sum'
		                            
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingProductNum',
		                            text: '产品规格代码'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingPrice',
		                            text: '单价',
		                            summaryType: 'sum'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingWeight',
		                            text: '支重',
		                            summaryType: 'sum'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingNumber',
		                            text: '数量',
		                            summaryType: 'sum'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingAllWeight',
		                            text: '总重',
		                            summaryType: 'sum'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'loggingPgNum',
		                            text: '次数',
		                            summaryType: 'sum'
		                        },
		                        {
		                            xtype: 'gridcolumn',
		                            dataIndex: 'note',
		                            text: '说明'
		                        }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    store:'LoggingStore',
                                    displayInfo: true
                                }
                            ],
                            features: [
                               {
                            	   groupHeaderTpl:  '员工姓名: {name} ({rows.length} 条)',
                            	   ftype: 'groupingsummary'
                               }
                           ]
                            
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});