/*
 * File: record/view/ShowWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Resigned.view.ShowWindow', {
    extend: 'Ext.window.Window',

    height: HEIGHT*0.5,
    id: 'ShowWindow',
    width: WIDTH*0.5,
    layout: {
    type : 'fit'
	},
	title : '查看图片',
	maximizable : true,
	modal : true,

	initComponent : function() {
		var me = this;

		Ext.applyIf(me, {
			items : [ {
				xtype : 'container',
				layout : {
					type : 'border'
				},
				items : [ {
					xtype : 'toolbar',
					region : 'north',
					margin : 2,
					items : [ {
						xtype : 'button',
						text : '导出',
						icon:'img/export.png',
						id:'exportBtn'
					}, {
						xtype : 'button',
						text : '关闭',
						icon:'img/close.png',
						id:'closeShowWindowBtn'
					} ]
				}, {
                    xtype: 'container',
                    region: 'center',
                    margin: '0 2 2 2 ',
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'image',
                            id: 'pic',
                            margin: '0 2 2 2'
                        }
                    ]
                } ]
			} ]
		});

		me.callParent(arguments);
	}

});