/*
 * File: role/view/RolePowerWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Role.view.RolePowerWindow', {
    extend: 'Ext.window.Window',

    id: 'RolePowerWindow',
    width: 340,
    layout: {
        type: 'fit'
    },
    title: '权限分配',
    x:200,
    y:50,
    modal: true,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
        	 items: [
                     {
                         xtype: 'container',
                         items: [
                             {
                                 xtype: 'treepanel',
                                 height: 400,
                                 region: 'center',
                                 id: 'RolePowerTreePanel',
                                 header: false,
                                 title: '功能权限类别树',
                                 rootVisible: false,
                                 store:'AuthorityStore',
                                 margin:2
                             },
                             {
                                 xtype: 'toolbar',
                                // height: 40,
                                 margin: 2,
                                 items: [
                                         '->',
                                         {
                 		                    xtype: 'button',
                 		                    icon: 'img/folder.gif',
                 		                    id:'Role_folder_btn',
                 		                    hidden:exists('Role_folder_btn'),
                 		                    text: '折叠'
                 		                },
                 		                {
                 		                    xtype: 'button',
                 		                    icon: 'img/folder-open.gif',
                 		                    id:'Role_folder_open_btn',
                 		                    hidden:exists('Role_folder_open_btn'),
                 		                    text: '展开'
                 		                },
                                         {
                                             xtype: 'button',
                                             id: 'Role_power_save_btn',
                                             icon: 'img/save.png',
                                             hidden:exists('Role_power_save_btn'),
                                             text: '保存'
                                         },
                                         {
                                             xtype: 'button',
                                             id: 'Role_power_close_btn',
                                             icon: 'img/close.png',
                                             hidden:exists('Role_power_close_btn'),
                                             text: '关闭'
                                         }
                                     ]
                             }
                         ]
                     }
                 ]
             });
        me.callParent(arguments);
    }

});