/*
 * File: model/view/ModelWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Model.view.ModelWindow', {
	extend : 'Ext.window.Window',

	id : 'ModelWindow',
	width : 500,
	layout : {
		type : 'fit'
	},
	title : '模块属性',
    resizable: false,
	modal : true,
	initComponent : function() {
		var me = this;

		Ext.applyIf(me, {
			items : [ {
				xtype : 'container',
				items : [ {
					xtype : 'form',
					frame : true,
					id : 'ModelForm',
					margin : 2,
					region : 'center',
					bodyPadding : 10,
					header : false,
					title : '属性表单',
					trackResetOnLoad : true,
					items : [ {
						xtype : 'textfield',
						anchor : '100%',
						hidden : true,
						fieldLabel : '模型id',
						name : 'modelUuid'
					}, {
						xtype : 'textfield',
						anchor : '100%',
						fieldLabel : '标题',
						name : 'modelTitle',
						allowBlank : false,
						blankText : '不能为空'
					}, {
						xtype : 'textfield',
						anchor : '100%',
						fieldLabel : '图标',
						name : 'modelIcon'
					}, {
						xtype : 'textfield',
						anchor : '100%',
						fieldLabel : 'LOGO',
						name : 'modelLogo'
					}, {
						xtype : 'combobox',
						anchor : '100%',
						fieldLabel : '状态',
						name : 'modelState',
						allowBlank : false,
						blankText : '不能为空',
						displayField : 'text',
						valueField : 'id',
						editable : false, // 启用编辑，主要是为了清空当前的选择项
						store : 'ModelStateStore',
						listeners : {
							afterrender : function(combol) {
								// var firstValue
						// =combol.store.proxy.data[0].id;
						// combol.setValue(firstValue);
					}
				}
					}, {
						xtype : 'treepicker',
						anchor : '100%',
						fieldLabel : '所属子系统',
						name : 'modelSubsystemUuid',
						id : 'modelSubsystemUuid',
						allowBlank : false,
						blankText : '不能为空',
						displayField : 'text',
						valueField : 'id',
						minPickerHeight : 20, // 最小高度，不设置的话有时候下拉会出问题
						editable : false, // 启用编辑，主要是为了清空当前的选择项
						autoScroll : true,
						// enableKeyEvents: true, //激活键盘事件
						forceSelection : true,// 只能选择下拉框里面的内容
						rootVisible : false,
						store : new Ext.data.TreeStore( {
							autoLoad : true,
							proxy : {
								type : 'ajax',
								url : 'sub/getSubsystemTreeList.do', // 请求url
								reader : {
									type : 'json'
								}
							},
							root : {
								text : '根目录',
								id : DEFAULT_ROOT_UUID
							},
							scope : this
						})
					}, {
						xtype : 'numberfield',
						anchor : '100%',
						fieldLabel : '排序',
						name : 'modelOrderby',
						allowBlank : false,
						blankText : '不能为空'
					}, {
						xtype : 'textareafield',
						anchor : '100%',
						height : 94,
						fieldLabel : '备注信息',
						name : 'modelNote'
					} ]
				}, {
					xtype : 'toolbar',
					//height : 40,
					margin : 2,
					items : [
					 '->',
				    {
						xtype : 'button',
						icon : 'img/save.png',
						id : 'Model_save_btn',
						hidden : exists('Model_save_btn'),
						text : '保存'
					}, {
						xtype : 'button',
						margin : '0 10 0 10',
						id : 'Model_close_btn',
						icon : 'img/close.png',
						hidden : exists('Model_close_btn'),
						text : '关闭'
					} ]
				} ]
			} ]

		});
		me.callParent(arguments);
	}

});