/*
 * File: org/model/OrgModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Org.model.OrgModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'orgUuid'
        },
        {
            name: 'orgName'
        },
        {
            name: 'orgCode'
        },
        {
            name: 'orgIcon'
        },
        {
            name: 'orgGradeUuid'
        },
        {
            name: 'orgGradeText'
        },
        {
            name: 'orgParentUuid'
        },
        {
            name: 'orgParentName'
        },
        {
            name: 'orgState'
        },
        {
            name: 'orgStateText'
        },
        {
            name: 'orgOrderBy'
        },
        {
            name: 'orgNote'
        },
        {
            name: 'createTime'
        },
        {
        	name:'child'
        },
        {
        	name:'startNumber'
        },
        {
        	name:'endNumber'
        }
    ]
});