/*
 * File: subsystem/controller/SubSystemController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Subsystem.controller.SubSystemController', {
    extend: 'Ext.app.Controller',

    id: 'SubSystemController',
    models: [
        'SubSystemModel'
    ],
    stores: [
        'SubSystemStore',
        'SubStateStore'
    ],
    views: [
        'SubsystemViewport',
        'SubSystemWindow'
    ],

    //刷新按钮
    onSub_refresh_btnClick: function(button, e, eOpts) {
		Ext.getCmp("SubSystemGridPanel").store.load();
    },

    //添加按钮
    onSub_add_btnClick: function(button, e, eOpts) {
        Ext.create("Subsystem.view.SubSystemWindow",{title:'添加子系统',icon:'img/add.png'}).show();
    },

    //保存按钮
    onSub_save_btnClick: function(button, e, eOpts) {
	 var formPanel =  Ext.getCmp("SubSystemForm");
   	 if(!formPanel.isDirty()){
   		 Ext.getCmp("SubSystemWindow").close();
		 return;
   	 }
   	 if(formPanel.isValid()){
   		 Ext.MessageBox.confirm("提示信息", "确定要保存吗？", function (btnId) {
    			if(btnId=='yes'){
    				 formPanel.submit({
        				 url:'sub/addSubsystem.do',
    		             method:'POST',
    		             waitTitle : "提示",
    		             waitMsg: '正在提交数据，请稍后...',
    		             success: function(form, action){
    		        	    var result = JSON.parse(action.response.responseText); 
    		            	if(result.success){
    		            		 Ext.Msg.show({title : '提示信息',msg :'操作成功!',buttons : Ext.Msg.OK,icon : Ext.MessageBox.INFO});
    		            		 Ext.getCmp("SubSystemWindow").close();
    		            		 Ext.getCmp("SubSystemGridPanel").store.load();
    		            	}else{
    		            		 Ext.Msg.show({title : '提示信息',msg :'操作失败!',buttons : Ext.Msg.OK,icon : Ext.MessageBox.INFO});
    		            	}
    		            },
    		            failure: function(form, action){
    		            	onActionFailureTypeShow(action);
    		            },
    		            scope:this
        			 });
    			}
    		 },this);
	 	}
    },

    //关闭按钮
    onSub_close_btnClick: function(button, e, eOpts) {
        Ext.getCmp("SubSystemWindow").close();
    },

    //修改按钮
    onSub_upd_btnClick: function(button, e, eOpts) {
    	var gridPanel = Ext.getCmp("SubSystemGridPanel");
        var selectionModel = gridPanel.getSelectionModel();
        if(selectionModel.getCount()<=0){
            Ext.Msg.show({
				title : '提示信息',
				msg :'请先选择一条子系统信息!',
				buttons : Ext.Msg.OK,
				icon : Ext.MessageBox.WARNING
			});
            return;
        }
        Ext.create("Subsystem.view.SubSystemWindow",{title:'修改子系统',icon:'img/update.png'}).show();
        Ext.getCmp("SubSystemForm").loadRecord(selectionModel.getSelection()[0]);
        Ext.getCmp("subKey").setReadOnly(true);
	    Ext.getCmp("subKey").setFieldStyle('background:#f2f2f2');
    },

    //删除按钮
    onSub_del_btnClick: function(button, e, eOpts) {
    	var gridPanel = Ext.getCmp("SubSystemGridPanel");
        var selectionModel = gridPanel.getSelectionModel();
        if(selectionModel.getCount()<=0){
            Ext.Msg.show({
				title : '提示信息',
				msg :'请先选择一条子系统信息!',
				buttons : Ext.Msg.OK,
				icon : Ext.MessageBox.WARNING
			});
            return;
        }
        var data = selectionModel.getSelection()[0].data;
        if(data.child>0){
        	 Ext.Msg.show({
 				title : '提示信息',
 				msg :'请先删除子系统下模块信息',
 				buttons : Ext.Msg.OK,
 				icon : Ext.MessageBox.WARNING
 			});
        	 return;
        }
        Ext.MessageBox.confirm("提示信息", "确定要删除吗？", function (btnId) {
            if (btnId == "yes") {
           	 Ext.Msg.wait('正在处理数据，请稍候...','提示');
                Ext.Ajax.request({
            		url:"sub/delSubsystem.do",
            		method:"POST",
            		params:data,
            		success:function(responst){
                		Ext.Msg.hide();
            			var result = JSON.parse(responst.responseText); 
            			if(result.success){
            				 Ext.Msg.show({
                  				title : '提示信息',
                  				msg :'删除成功!',
                  				buttons : Ext.Msg.OK,
                  				icon : Ext.MessageBox.INFO
                  			 });     
            				 Ext.getCmp("SubSystemGridPanel").store.load();
            			}else{
            				 Ext.Msg.show({
               				title : '提示信息',
               				msg :'删除失败!',
               				buttons : Ext.Msg.OK,
               				icon : Ext.MessageBox.ERROR
               			 });     
            			}
            		},
        		    failure: function(from,action){
            			Ext.Msg.hide();
            			onActionFailureTypeShow(action);
            		},
            		scope:this
            	});
            }
        },this);
    },
    //定时器,解决单击事件双击事件问题
    task:new Ext.util.DelayedTask(),
    //双击事件
    onSubSystemGridPanelCellDblClick:function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts){
    	Ext.create("Subsystem.view.SubSystemWindow",{title:'修改子系统',icon:'img/update.png'}).show();
        Ext.getCmp("SubSystemForm").loadRecord(record);
        Ext.getCmp("subKey").setReadOnly(true);
	    Ext.getCmp("subKey").setFieldStyle('background:#f2f2f2');
    },
    //单击事件
    onSubSystemGridPanelCellClick:function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts){
		Ext.getCmp("Sub_upd_btn").enable(true);
		if(record.data.child>0){
			Ext.getCmp("Sub_del_btn").setDisabled(true);
		}else{
			Ext.getCmp("Sub_del_btn").enable(true);
		}
    },
    //唯一标识校验
    onSubKeyTextfieldBlur: function(component, e, eOpts) {
    	if(component.value==null||component.value==""){
    		return;
    	}
    	if(component.originalValue == component.value){
    		return;
    	}
    	Ext.Ajax.request({
    		url:"sub/validateSubKey.do",
     		method:"POST",
     		params:{
        	 	'subKey':component.value
         	},
     		success:function(responst){
     			var result = JSON.parse(responst.responseText); 
     			if(result.success){
     				Ext.Msg.show({
        				title : '提示信息',
        				msg : '该数据标识已经存在，请重新输入！',
        				buttons : Ext.Msg.OK,
        				icon : Ext.MessageBox.WARNING
        			 });
     				component.focus();
     				component.setValue("");
     			}
     		},
 		    failure: function(from,action){
     			onActionFailureTypeShow(action);
     		},
     		scope:this
    	});
    },
    init: function(application) {
        this.control({
            "button[id=Sub_refresh_btn]": {
                click: this.onSub_refresh_btnClick
            },
            "button[id=Sub_add_btn]": {
                click: this.onSub_add_btnClick
            },
            "button[id=Sub_save_btn]": {
                click: this.onSub_save_btnClick
            },
            "button[id=Sub_close_btn]": {
                click: this.onSub_close_btnClick
            },
            "button[id=Sub_upd_btn]": {
                click: this.onSub_upd_btnClick
            },
            "button[id=Sub_del_btn]": {
                click: this.onSub_del_btnClick
            },
            "#SubSystemGridPanel":{
            	cellclick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts){
					this.task.delay(200,this.onSubSystemGridPanelCellClick,this,new Array(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts));
	    		},
	    		celldblclick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts){
	    			this.task.delay(200,this.onSubSystemGridPanelCellDblClick,this,new Array(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts));
	    		}
            },
            "textfield[id=subKey]": {
                blur: this.onSubKeyTextfieldBlur
            }
        });
    }

});
