/*
 * File: workCheck/view/sigleWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WorkCheck.view.sigleWindow', {
    extend: 'Ext.window.Window',

    height: 438,
    id: 'sigleWindow',
    width: 584,
    layout: {
        type: 'fit'
    },
    title: '添加月度考核',
    modal:true,
    resizable: false,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'south',
                            margin: '0 2 2 2',
                            items: [
                                '->',
                                {
                                    xtype: 'button',
                                    icon:'img/save.png',
                                    id:'WorkCheckSaveBtn',
                                    text: '保存'
                                },
                                {
                                    xtype: 'button',
                                    icon:'img/close.png',
                                    id:'WorkCheckCloseBtn',
                                    text: '关闭'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'center',
                            frame: true,
                            margin: 2,
                            bodyPadding: 10,
                            header: false,
                            title: '个人考勤',
                            id:'WorkCheckFormPanel',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 103,
                                    layout: {
                                        columns: 2,
                                        type: 'table'
                                    },
                                    title: '考勤时间',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: '考勤年度',
                                            name:'wcYear',
                                            id:'wcYear',
                                            allowBlank: false,
                                            blankText: '不能为空',
                                            value:new Date().getFullYear(),
                                            maxLength: 4,
                                            minLength: 4
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: '考勤月份',
                                            name:'wcMonth',
                                            id:'wcMonth',
                                            allowBlank: false,
                                            blankText: '不能为空',
                                            editable: false,
                                            store:Ext.create("Ext.data.Store",{
	                                           	 fields: ['id', 'text'],
	                                           	 autoLoad:true,
	                                           	 data : [
	                                           	         {"id":1, "text":"一月"},
	                                           	         {"id":2, "text":"二月"},
	                                           	         {"id":3, "text":"三月"},
	                                           	         {"id":4, "text":"四月"},
	                                           	         {"id":5, "text":"五月"},
	                                           	         {"id":6, "text":"六月"},
	                                           	         {"id":7, "text":"七月"},
	                                           	         {"id":8, "text":"八月"},
	                                           	         {"id":9, "text":"九月"},
	                                           	         {"id":10, "text":"十月"},
	                                           	         {"id":11, "text":"十一月"},
	                                           	         {"id":12, "text":"十二月"}
	                                           	     ]
                                           }),
                                           displayField: 'text',
                                           valueField: 'id',
                                           listeners:{
										      	beforerender:function(combol){
                                        			var m = new Date().getMonth();
                                        			if(m==0){
                                        				Ext.getCmp("wcYear").setValue(new Date().getFullYear()-1);
                                        				m=12;
                                        			}else{
                                        				m=m+1;
                                        			}
                                        			combol.setValue(m);
										      	}
											}
                                           
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: '考勤开始时间',
                                            name:'wcStartDate',
                                            id:'wcStartDate',
                                            allowBlank: false,
                                            format:'Y-m-d',
                                            blankText: '不能为空'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: '考勤结束时间',
                                            name:'wcEndDate',
                                            id:'wcEndDate',
                                            allowBlank: false,
                                            format:'Y-m-d',
                                            blankText: '不能为空'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: '满勤天数',
                                            name:'wcAllDay',
                                            id:'wcAllDay',
                                            allowBlank: false,
                                            blankText: '不能为空',
                                            value:27
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 124,
                                    layout: {
                                        columns: 2,
                                        type: 'table'
                                    },
                                    title: '考勤人员',
                                    items: [
										{
										    xtype: 'hiddenfield',
										    fieldLabel: '员工uuid',
										    name:'userUuid',
										    id:'userUuid',
										    allowBlank: false,
										    blankText: '不能为空'
										    
										},
										{
										    xtype: 'hiddenfield',
										    fieldLabel: '主键Uuid',
										    name:'uuid',
										    id:'uuid'
										    
										},
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '员工工号',
                                            name:'userNumber',
                                            id:'userNumber',
                                            listeners : {
												specialKey : function(field, e) {
													if (e.getKey() == Ext.EventObject.ENTER) {//响应回车  
														Ext.getCmp("wcCheckDay").focus();
														Ext.getCmp("wcCheckDay").focus();
							                        }  
												}  
											}  
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '员工姓名',
                                            name:'userName',
                                            id:'userName',
                                            readOnly:true,
                                            fieldStyle:'background:#f2f2f2'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '所属部门',
                                            name:'orgName',
                                            id:'orgName',
                                            readOnly:true,
                                            fieldStyle:'background:#f2f2f2'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            fieldLabel: '所属部门',
                                            name:'orgUuid',
                                            id:'orgUuid'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            fieldLabel: '入职时间',
                                            name:'joinTime',
                                            id:'joinTime'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '职务',
                                            name:'roleName',
                                            id:'roleName',
                                            readOnly:true,
                                            fieldStyle:'background:#f2f2f2'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: '考勤天数',
                                            name:'wcCheckDay',
                                            id:'wcCheckDay',
                                            allowBlank: false,
                                            blankText: '不能为空',
                                            listeners : {
												specialKey : function(field, e) {
													if (e.getKey() == Ext.EventObject.ENTER) {//响应回车  
														Ext.getCmp("wcAddDay").focus()
							                        }  
												}  
											}  
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: '加班天数',
                                            name:'wcAddDay',
                                            id:'wcAddDay',
                                          
                                            listeners : {
												specialKey : function(field, e) {
													if (e.getKey() == Ext.EventObject.ENTER) {//响应回车  
														Ext.getCmp("wcAddHour").focus()
							                        }  
												}  
											}  
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: '加班小时',
                                            name:'wcAddHour',
                                            id:'wcAddHour',
                                            listeners : {
												specialKey : function(field, e) {
													if (e.getKey() == Ext.EventObject.ENTER) {//响应回车  
														Ext.getCmp("wcNote").focus()
							                        }  
												}  
											}  
                                        }
                                        
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 90,
                                    title: '备注信息',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            fieldLabel: '备注信息',
                                            name:'wcNote',
                                            id:'wcNote'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});