/*
 * File: workCheck/view/WorkCheckWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WorkCheck.view.WorkCheckWindow', {
    extend: 'Ext.window.Window',

    height: 480,
    id: 'WorkCheckWindow',
    width: 591,
    layout: {
        type: 'fit'
    },
    title: '月度考勤',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            region: 'center',
                            frame: true,
                            margin: 2,
                            bodyPadding: 10,
                            header: false,
                            title: '月度考勤表单',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 107,
                                    layout: {
                                        columns: 2,
                                        type: 'table'
                                    },
                                    title: '考勤时间',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '考勤年度'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '考勤月份'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '考勤开始时间'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '考勤结束时间'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '满勤天数'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 272,
                                    autoScroll: true,
                                    title: '考勤人员',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            header: false,
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 69,
                                                    dataIndex: 'string',
                                                    text: '员工号'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 62,
                                                    dataIndex: 'string',
                                                    text: '姓名'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 101,
                                                    dataIndex: 'string',
                                                    text: '职务'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 70,
                                                    dataIndex: 'string',
                                                    text: '考勤天数'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 89,
                                                    dataIndex: 'string',
                                                    text: '加班天数/小时'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 129,
                                                    dataIndex: 'string',
                                                    text: '备注'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 129,
                                                    dataIndex: 'string',
                                                    text: '入职时间'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            region: 'south',
                            margin: '0 2 2 2',
                            items: [
                                {
                                    xtype: 'button',
                                    icon: 'img/save.png',
                                    text: '保存'
                                },
                                {
                                    xtype: 'button',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});