/*
 * File: logging/store/MyJsonStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Logging.store.LoggingStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Logging.model.Logging'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Logging.model.Logging',
            storeId: 'LoggingStore',
            groupField: 'orgName',
            proxy: {
        	 type: 'ajax',
             url: 'logging/getLoggingPage.do',
             reader: {
    			type: 'json',
	   	  	 	//数据格式为json   
	            root: 'data',
	            //获取数据总数 
	            totalProperty:'dataSize'
               }
            }
        }, cfg)]);
    }
});