/*
 * File: resigned/view/ResignedWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('User.view.ResignedWindow', {
    extend: 'Ext.window.Window',

    height: HEIGHT*0.6,
    width: 780,
    layout: {
        type: 'fit'
    },
    title: '辞职员工登记',
    maximizable: true,
    modal: true,
    id:'ResignedWindow',
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            region: 'center',
                            frame: true,
                            margin: 2,
                            bodyPadding: 10,
                            header: false,
                            title: '辞职员工表单',
                            id:'ResignedFormPanel',
                            trackResetOnLoad:true,
                            autoScroll: true,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 220,
                                    margin: 5,
                                    title: '辞职员工基本信息',
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 26,
                                            layout: {
                                                align: 'middle',
                                                pack: 'center',
                                                type: 'hbox'
                                            },
                                            items: [
												{
												    xtype: 'hiddenfield',
												    flex: 1,
												    margin: '0 0 2 0',
												    name:'userUuid',
												    fieldLabel: '员工uuid'
												},
												{
												    xtype: 'hiddenfield',
												    flex: 1,
												    margin: '0 0 2 0',
												    name:'resUuid',
												    fieldLabel: '主键'
												},
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 0 2 0',
                                                    name:'userName',
                                                    fieldLabel: '员工姓名',
                                                    fieldStyle: 'background:#f2f2f2',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 0 2 10',
                                                    name:'userNumber',
                                                    fieldLabel: '员工工号',
                                                    fieldStyle: 'background:#f2f2f2',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 26,
                                            layout: {
                                                align: 'middle',
                                                pack: 'center',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 0 2 0',
                                                    name:'roleName',
                                                    fieldLabel: '职务'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 0 2 10',
                                                    name:'userGenderText',
                                                    fieldLabel: '性别'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 26,
                                            layout: {
                                                align: 'middle',
                                                pack: 'center',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    flex: 1,
                                                    margin: '0 0 2 0',
                                                    format:'Y-m-d',
                                                    name:'resApplyDate',
                                                    //editable: false,
                                                    fieldLabel: '申请辞职时间'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    flex: 1,
                                                    margin: '0 0 2 10',
                                                    name:'resApproveDate',
                                                    fieldLabel: '批准辞职时间',
                                                    editable: false,
                                                    format:'Y-m-d',
                                                    allowBlank: false,
                                                    blankText: '不能为空',
                                                    value:new Date()
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 26,
                                            layout: {
                                                align: 'middle',
                                                pack: 'center',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    margin: '0 0 2 0',
                                                    name:'resType',
                                                    fieldLabel: '离职类别',
                                                    displayField: 'text',
												    valueField: 'id',
												    allowBlank: false,
                                                    blankText: '不能为空',
												    editable: false,//启用编辑，主要是为了清空当前的选择项
												    store:'ResignedTypeStore',
												    listeners:{
												      	afterrender:function(combol){
												        	var firstValue =combol.getStore().data.items[0].data.id;
															combol.setValue(firstValue);  
												      	}
													}
                                                   
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    margin: '0 0 2 10',
                                                    name:'resMoneyType',
                                                    fieldLabel: '工资结算方式',
                                                    displayField: 'text',
												    valueField: 'id',
												    allowBlank: false,
                                                    blankText: '不能为空',
												    editable: false,//启用编辑，主要是为了清空当前的选择项
												    store:'ResignedMoneyTypeStore',
												    listeners:{
												      	afterrender:function(combol){
															//var index=combol.store.find('text',combol.value);
												        	var firstValue =combol.getStore().data.items[0].data.id;
															combol.setValue(firstValue);  
												      	}
													}
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 26,
                                            layout: {
                                                align: 'middle',
                                                pack: 'center',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 0 2 0',
                                                    name:'userMobile',
                                                    fieldLabel: '联系方式'
                                                },
                                                {

                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    margin: '0 0 2 10',
                                                    name:'userBankCard',
                                                    fieldLabel: '是否有工资卡',
                                                    displayField: 'text',
												    valueField: 'id',
												    allowBlank: false,
                                                    blankText: '不能为空',
												    editable: false,//启用编辑，主要是为了清空当前的选择项
												    store:'BankCardStateStore',
												    listeners:{
												      	afterrender:function(combol){
															//var index=combol.store.find('text',combol.value);
												        	var firstValue =combol.getStore().data.items[0].data.id;
															combol.setValue(firstValue);  
												      	}
													}
                                                
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            name:'resReson',
                                            fieldLabel: '辞职原因'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 320,
                                    margin: 5,
                                    title: '辞职员工交接项目',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 30,
                                            name:'resHandOver',
                                            fieldLabel: '工作交接情况'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 30,
                                            name:'resToolReturn',
                                            fieldLabel: '工具归还情况'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 30,
                                            name:'resOfficeGoods',
                                            fieldLabel: '办公物品归还情况'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 30,
                                            name:'resCheckWork',
                                            fieldLabel: '考勤情况'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            name:'resCheckWorkNum',
                                            minValue: 0,
                                            fieldLabel: '考勤天数'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 30,
                                            name:'resFinancialLoan',
                                            fieldLabel: '财务借款情况'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 30,
                                            name:'resDeductWageItem',
                                            fieldLabel: '扣款项目'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            name:'resDeductWages',
                                            minValue: 0,
                                            fieldLabel: '应扣金额'
                                        },
                                        /*
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            name:'resRealyWages',
                                            minValue: 0,
                                            fieldLabel: '实际领取工资'
                                        },
                                        */
                                        {
                                            xtype: 'checkboxgroup',
                                            height: 28,
                                            fieldLabel: '待发工资月份',
                                            id:'month',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '1',
                                                    boxLabel: '1月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '2',
                                                    boxLabel: '2月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '3',
                                                    boxLabel: '3月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '4',
                                                    boxLabel: '4月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '5',
                                                    boxLabel: '5月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '6',
                                                    boxLabel: '6月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '7',
                                                    boxLabel: '7月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '8',
                                                    boxLabel: '8月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '9',
                                                    boxLabel: '9月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '10',
                                                    boxLabel: '10月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '11',
                                                    boxLabel: '11月'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name:'month',
                                                    inputValue: '12',
                                                    boxLabel: '12月'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 120,
                                    margin: 5,
                                    title: '备注说明',
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            anchor: '100%',
                                            fieldLabel: '附件上传',
                                            name:'file',
                                            buttonText: '浏览..'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 64,
                                            name:'resNote',
                                            fieldLabel: '备注说明'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            region: 'south',
                            margin: '0 2 2 2 ',
                            items: [
                                '->',
                                {
                                    xtype: 'button',
                                    icon:'img/save.png',
                                    id:'ResignedSaveBtn',
                                    text: '保存'
                                },
                                {
                                    xtype: 'button',
                                    icon:'img/close.png',
                                    id:'ResignedCloseBtn',
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});