/*
 * File: user/view/UserViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('User.view.UserViewport', {
    extend: 'Ext.container.Viewport',

    id: 'UserViewport',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    region: 'north',
                    //height: 40,
                    margin: 2,
                    items: [
                        {
                            xtype: 'button',
                            id: 'User_refresh_btn',
                            icon: 'img/reload.png',
                            hidden:exists('User_refresh_btn'),
                            text: '刷新'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_refresh_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_folding_btn',
                            icon: 'img/folder.gif',
                            hidden:exists('User_folding_btn'),
                            text: '折叠'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_folding_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_folder_open_btn',
                            icon: 'img/folder-open.gif',
                            hidden:exists('User_folder_open_btn'),
                            text: '展开'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_folder_open_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_add_btn',
                            icon: 'img/add.png',
                            disabled:true,
                            hidden:exists('User_add_btn'),
                            text: '添加'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_add_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_upd_btn',
                            icon: 'img/update.png',
                            hidden:exists('User_upd_btn'),
                            disabled:true,
                            text: '修改'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_upd_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_del_btn',
                            icon: 'img/del.png',
                            disabled:true,
                            hidden:exists('User_del_btn'),
                            text: '删除'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_del_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_reset_password_btn',
                            icon: 'img/application_key.png',
                            disabled:true,
                            hidden:exists('User_reset_password_btn'),
                            text: '重置密码'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_reset_password_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_upd_org_btn',
                            icon: 'img/changeOrg.png',
                            disabled:true,
                            hidden:exists('User_upd_org_btn'),
                            text: '部门变更'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_upd_org_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_role_set_btn',
                            icon: 'img/user.png',
                            disabled:true,
                            hidden:exists('User_role_set_btn'),
                            text: '分配角色(人员)'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_role_set_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_org_role_set_btn',
                            icon: 'img/group.png',
                            disabled:true,
                            hidden:exists('User_org_role_set_btn'),
                            text: '分配角色(部门)'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('User_org_role_set_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_resigned_btn',
                            icon: 'img/delete.png',
                            disabled:true,
                            //hidden:exists('User_org_role_set_btn'),
                            text: '辞职'
                        },
                        {
                        	xtype: 'tbseparator'
                        	//hidden:exists('User_org_role_set_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'User_show_form_btn',
                            icon: 'img/search.png',
                            hidden:exists('User_show_form_btn'),
                            text: '高级查询'
                        }
                        
                    ]
                },
                {
                    xtype: 'treepanel',
                    region: 'west',
                    split: true,
                    id: 'OrgTreePanel',
                    margin: '0 0 2 2',
                    width: 200,
                    collapsed: false,
                    collapsible: true,
                    title: '组织机构',
                    store: 'OrgTreeStore',
                    rootVisible: false,
                    viewConfig: {

                    }
                },
                {
                    xtype: 'container',
                    region: 'center',
                    margin: '0 2 2 0',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            region: 'north',
                            frame: true,
                            height: 80,
                            margin: '0 0 2 0',
                            layout: {
                                type: 'column'
                            },
                            bodyPadding: 10,
                            id:'searchForm',
                            hidden:true,
                            title: '高级查询',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '用户帐号',
                                    labelWidth: 70,
                                    name: 'userId',
                                    hidden:true,
                                    id:'userId'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 0 10',
                                    fieldLabel: '用户名称',
                                    labelWidth: 70,
                                    name: 'userName',
                                    id:'userName'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 0 10',
                                    fieldLabel: '员工号',
                                    labelWidth: 50,
                                    name: 'userNumber',
                                    id:'userNumber'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 0 5',
                                    width: 120,
                                    fieldLabel: '状态',
                                    labelWidth: 50,
                                    name: 'userState',
                                    displayField: 'text',
                                    valueField: 'id',
                                    editable: false, //启用编辑，主要是为了清空当前的选择项
                                    store:'UserStateStore',
                                    id:'userState',
                                    listeners:{
                                      	afterrender:function(combol){
                                      		//var firstValue =combol.store.proxy.data[0].id;
                                      		//combol.setValue(firstValue);  
                                      	}
                                	}
                                },
                                {
                                    xtype: 'button',
                                    id: 'User_search_btn',
                                    margin: '0 0 0 10',
                                    icon: 'img/search.png',
                                    hidden:exists('User_search_btn'),
                                    text: '查询'
                                },
                                {
                                    xtype: 'button',
                                    id: 'User_reset_btn',
                                    margin: '0 0 0 10',
                                    icon: 'img/reset.png',
                                    hidden:exists('User_reset_btn'),
                                    text: '重置'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            title: '人员管理',
                            id:'UserGridPanel',
                            store: Ext.create("User.store.UserGridPanelStore",{autoLoad:true}),
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 46,
                                    width:'auto',
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 82,
                                    dataIndex: 'userName',
                                    width:'auto',
                                    text: '名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userId',
                                    hidden: true,
                                    width:'auto',
                                    text: '帐号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userNumber',
                                    width:'auto',
                                    text: '员工号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'roleName',
                                    width:'auto',
                                    text: '角色职称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'sfz',
                                    text: '身份证复印件',
                                    width:'auto',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                                		if(null!=data){
                                			return "<a href='javascript:void(0);'>查看</a>&nbsp;|&nbsp;<a href='javascript:void(0);'>删除</a>";
                                		}else{
                                			return "<a href='javascript:void(0);' style='color:red'>上传</a>";
                                		}
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'tjzm',
                                    text: '体检报告',
                                    width:'auto',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
	                                	if(null!=data){
	                                		return "<a href='javascript:void(0);'>查看</a>&nbsp;|&nbsp;<a href='javascript:void(0);'>删除</a>";
	                            		}else{
                                			return "<a href='javascript:void(0);' style='color:red'>上传</a>";
	                            		}
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'rzbg',
                                    text: '入职应聘表',
                                    width:'auto',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
	                                	if(null!=data){
	                                		return "<a href='javascript:void(0);'>查看</a>&nbsp;|&nbsp;<a href='javascript:void(0);'>删除</a>";
	                            		}else{
                                			return "<a href='javascript:void(0);' style='color:red'>上传</a>";
	                            		}
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'sqzzb',
                                    text: '申请转正表',
                                    width:'auto',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
	                                	if(null!=data){
	                                		return "<a href='javascript:void(0);'>查看</a>&nbsp;|&nbsp;<a href='javascript:void(0);'>删除</a>";
	                            		}else{
                                			return "<a href='javascript:void(0);' style='color:red'>上传</a>";
	                            		}
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userMobile',
                                    width:'auto',
                                    text: '手机'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userGenderText',
                                    width:'auto',
                                    text: '性别'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userAge',
                                    width:'auto',
                                    text: '年龄'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'formalTime',
                                    width:'auto',
                                    text: '转正时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'idCard',
                                    width:'auto',
                                    text: '身份证号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userDegreesText',
                                    width:'auto',
                                    text: '学历'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userAddress',
                                    width:'auto',
                                    text: '籍贯/住址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userNormalPay',
                                    width:'auto',
                                    text: '(正)基本工资'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userMeritPay',
                                    width:'auto',
                                    text: '(正)绩效工资'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userOtherPay',
                                    width:'auto',
                                    text: '(正)其他工资'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userNote',
                                    width:'auto',
                                    text: '备注'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userOrderBy',
                                    width:'auto',
                                    text: '排序'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    store:'UserGridPanelStore',
                                    displayInfo: true
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});