/*
 * File: user/view/UserChangeOrgWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('User.view.UserChangeOrgWindow', {
    extend: 'Ext.window.Window',

    id: 'UserChangeOrgWindow',
    width: 350,
    layout: {
        type: 'fit'
    },
    title: '部门变更',
    modal: true,
    resizable: false,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
        	 items: [
                     {
                         xtype: 'container',
                         items: [
								{
								    xtype: 'treepanel',
								    dock: 'top',
								    height: 449,
								    header: false,
								    title: '组织机构树',
								    id:'UserOrgTreePanel',
								    margin:2,
								    viewConfig: {
								        frame: false,
								        rootVisible: false
								    }
								},
                             {
                                 xtype: 'toolbar',
                                 //height: 40,
                                 margin: 2,
                                 items: [
                                     '->',
									{
									    xtype: 'button',
									    icon: 'img/folder.gif',
									    id:'User_change_folder_btn',
									    hidden:exists('User_change_folder_btn'),
									    text: '折叠'
									},
									{
									    xtype: 'button',
									    icon: 'img/folder-open.gif',
									    id:'User_change_folder_open_btn',
									    hidden:exists('User_change_folder_open_btn'),
									    text: '展开'
									},
									{
									    xtype: 'button',
									    icon: 'img/save.png',
									    id:'User_change_save_btn',
									    hidden:exists('User_change_save_btn'),
									    text: '保存'
									},
									{
									    xtype: 'button',
									    icon: 'img/close.png',
									    id:'User_change_close_btn',
									    hidden:exists('User_change_close_btn'),
									    text: '关闭'
									}
                                 ]
                             }
                         ]
                     }
                 ]
             });
        me.callParent(arguments);
    }

});