/*
 * File: user/view/UserWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('User.view.UserWindow', {
    extend: 'Ext.window.Window',

    id: 'UserWindow',
    width: 640,
    resizable: false,
    autoScroll: true,
    layout: {
        type: 'fit'
    },
    title: '人员信息',
    modal: true,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
        	items: [
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'form',
                                frame: true,
                                margin: 2,
                                layout: {
                                    type: 'column'
                                },
                                bodyPadding: 10,
                                header: false,
                                region: 'center',
                                title: '人员信息表单',
                                id:'userForm',
                                trackResetOnLoad:true,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        height: 160,
                                        width: 582,
                                        title: '基本信息',
                                        items: [
                                            {
                                                xtype: 'hiddenfield',
                                                anchor: '100%',
                                                fieldLabel: 'uuid',
                                                name: 'userUuid'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                anchor: '100%',
                                                fieldLabel: 'orgUuid',
                                                name: 'orgUuid',
                                                id:'orgUuid'
                                            },
                                            /*
                                            {
                                                xtype: 'textfield',
                                                anchor: '100%',
                                                fieldLabel: '帐号',
                                                name: 'userId',
                                                id:'User_window_userId',
                                                vtype:'alpha',
                                                allowBlank: false,
                                                blankText: '不能为空'
                                            },
                                            */
                                            {
                                                xtype: 'container',
                                                height: 29,
                                                width: 567,
                                                layout: {
                                                    type: 'column'
                                                },
                                                items: [
                                                    {
                                                    	 xtype: 'textfield',
                                                         anchor: '100%',
                                                         fieldLabel: '帐号',
                                                         name: 'userId',
                                                         id:'User_window_userId',
                                                         //vtype:'alpha',
                                                         width: 270,
                                                         allowBlank: false,
                                                         blankText: '不能为空'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        margin: '0 0 0 20',
                                                        width: 270,
                                                        name: 'userNumber',
                                                        id:'User_window_userNumber',
                                                        allowBlank: false,
                                                        blankText: '不能为空',
                                                        maxLength: 3,//最大长度三位
                                                        fieldLabel: '员工号'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                height: 29,
                                                width: 567,
                                                layout: {
                                                    type: 'column'
                                                },
                                                items: [
                                                    {
		                                                xtype: 'textfield',
		                                                fieldLabel: '名称',
		                                                name: 'userName',
		                                                width: 270,
		                                                allowBlank: false,
		                                                blankText: '不能为空'
		                                            },
                                                    {
                                                        xtype: 'textfield',
                                                        margin: '0 0 0 20',
                                                        width: 270,
                                                        name: 'userMobile',
                                                        id:'userMobile',
                                                        fieldLabel: '手机号'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                height: 29,
                                                width: 567,
                                                layout: {
                                                    type: 'column'
                                                },
                                                items: [
													{
													    xtype: 'combobox',
													    anchor: '100%',
													    fieldLabel: '状态',
													    name: 'userState',
													    allowBlank: false,
													    blankText: '不能为空',
													    displayField: 'text',
													    valueField: 'id',
													    editable: false,//启用编辑，主要是为了清空当前的选择项
													    store:'UserStateStore',
													    width: 270,
													    listeners:{
													      	afterrender:function(combol){
																//var index=combol.store.find('text',combol.value);
													        	var firstValue =combol.getStore().data.items[0].data.id;
																combol.setValue(firstValue);  
													      	}
														}
													},
													{
		                                                xtype: 'textfield',
		                                                anchor: '100%',
		                                                fieldLabel: '身份证号',
		                                                name: 'idCard',
		                                                maxLength:18,
		                                                width: 270,
		                                                id:'idCard',
		                                                margin: '0 0 0 20',
		                                                //regex : /^(\d{18,18}|\d{15,15}|\d{17,17}x)$/,
		                                                regex : /^(\d{18,18}|\d{17,17}x)$/,
		                                                regexText : '输入正确的身份号码'
		                                            }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                height: 29,
                                                width: 567,
                                                layout: {
                                                    type: 'column'
                                                },
                                                items: [
													{
		                                                xtype: 'datefield',
		                                                anchor: '100%',
		                                                fieldLabel: '入职时间',
		                                                name: 'joinTime',
		                                                allowBlank: false,
		                                                blankText: '不能为空',
		                                                //editable: false,
		                                                format: 'Y-m-d',
		                                                width: 270
		                                            },
		                                            {
		                                                xtype: 'datefield',
		                                                anchor: '100%',
		                                                fieldLabel: '转正时间',
		                                                name: 'formalTime',
		                                                margin: '0 0 0 20',
													    width: 270,
		                                                //editable: false,
		                                                format: 'Y-m-d'
		                                            },
                                                ]
                                            },
                                            {

                                                xtype: 'container',
                                                height: 29,
                                                width: 567,
                                                layout: {
                                                    type: 'column'
                                                },
                                                items: [
													{
													    xtype: 'combobox',
													    anchor: '100%',
													    fieldLabel: '性别',
													    name: 'userGender',
													    id:'userGender',
													    allowBlank: false,
													    blankText: '不能为空',
													    displayField: 'text',
													    valueField: 'id',
													    width: 270,
													    editable: false,//启用编辑，主要是为了清空当前的选择项
													    store:'UserGenderStore'
													}
                                                ]
                                            
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        width: 582,
                                        layout: {
                                            type: 'column'
                                        },
                                        title: '其他信息',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                width:275,
                                                fieldLabel: '办公电话',
                                                margin: 2,
                                                name: 'userPhone'
                                            },
                                            {
                                                xtype: 'textfield',
                                                width:275,
                                                fieldLabel: '邮箱',
                                                margin: 2,
                                                name: 'userMail'
                                            },
                                            {
                                                xtype: 'textfield',
                                                width:275,
                                                fieldLabel: 'QQ/MSG',
                                                margin: 2,
                                                name: 'userOther'
                                            },
                                            {
                                                xtype: 'textfield',
                                                width:275,
                                                fieldLabel: '毕业院校',
                                                margin: 2,
                                                name: 'userUnversity'
                                            },
                                            {
                                                xtype: 'combobox',
                                                width:275,
                                                fieldLabel: '学历',
                                                displayField: 'text',
                                                valueField: 'id',
                                                name: 'userDegrees',
                                                store:'UserDegreesStore',
                                                margin: 2,
                                                editable: false//启用编辑，主要是为了清空当前的选择项
                                               
                                            },
                                            {
                                                xtype: 'textfield',
                                                width:275,
                                                fieldLabel: '籍贯/住址',
                                                margin: 2,
                                                name: 'userAddress'
                                            },
                                            {
                                                xtype: 'datefield',
                                                width:275,
                                                fieldLabel: '生日',
                                                name: 'userBirthday',
                                                id:'userBirthday',
                                                //editable: false,
                                                margin: '2 2 10 2',
                                                format: 'Y-m-d'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                width:275,
                                                fieldLabel: '排序',
                                                margin: '2 2 10 2',
                                                name: 'userOrderBy'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        width: 583,
                                        title: '备注说明',
                                        items: [
                                            {
                                                xtype: 'textareafield',
                                                anchor: '100%',
                                                height: 60,
                                                fieldLabel: '备注说明',
                                                name: 'userNote'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                            	 xtype: 'toolbar',
                                 //height: 40,
                                 margin: 2,
                                items: [
                                        '->',
                                     {
                                        xtype: 'button',
                                        id:'User_save_btn',
                                        icon: 'img/save.png',
                                        hidden:exists('User_save_btn'),
                                        text: '保存'
                                    },
                                    {
                                        xtype: 'button',
                                        id:'User_close_btn',
                                        icon: 'img/close.png',
                                        hidden:exists('User_close_btn'),
                                        text: '关闭'
                                    }
                                ]
                            }
                        ]
                    }
        ]
            });
        	
        me.callParent(arguments);
    }

});