/*
 * File: product/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Product.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    region: 'north',
                    //height: 40,
                    margin: 2,
                    items: [
						{
						    xtype: 'button',
						    id: 'product_refresh_btn',
						    icon: 'img/reload.png',
						    hidden:exists('product_refresh_btn'),
						    text: '刷新'
						},
						{
                        	xtype: 'tbseparator',
                        	hidden:exists('product_refresh_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'product_add_btn',
                            icon: 'img/add.png',
                            hidden:exists('product_add_btn'),
                            text: '添加'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('product_add_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'product_upd_btn',
                            icon: 'img/update.png',
                            hidden:exists('product_upd_btn'),
                            disabled:true,
                            text: '修改'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('product_upd_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'product_del_btn',
                            icon: 'img/del.png',
                            hidden:exists('product_del_btn'),
                            disabled:true,
                            text: '删除'
                        },
                        {
                        	xtype: 'tbseparator',
                        	hidden:exists('product_del_btn')
                        },
                        {
                            xtype: 'button',
                            id: 'product_show_search_btn',
                            icon: 'img/search.png',
                            hidden:exists('product_del_btn'),
                            text: '高级查询'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'north',
                    frame: true,
                    height: 79,
                    id: 'product_search_form',
                    margin: '0 2 2 2 ',
                    layout: {
                        type: 'column'
                    },
                    bodyPadding: 10,
                    animCollapse: false,
                    collapsed: false,
                    collapsible: false,
                    hidden: true,
                    title: '高级查询',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '名称',
                            name:'productName',
                            id:'productName',
                            labelWidth: 50
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '规格代码',
                            name:'productNum',
                            id:'productNum',
                            margin:'0 0 0 10',
                            labelWidth: 70
                        },
                        {
                            xtype: 'button',
                            id: 'product_search_btn',
                            margin: '0 0 0 10',
                            icon: 'img/search.png',
                            text: '查询'
                        },
                        {
                            xtype: 'button',
                            id: 'product_reset_btn',
                            margin: '0 0 0 10',
                            icon: 'img/reset.png',
                            text: '重置'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    id: 'product_gridpanel',
                    margin: '0 2 2 2',
                    title: '产品信息',
                    store: Ext.create("Product.store.ProductStore",{autoLoad:true}),
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 39,
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'productName',
                            text: '名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'productNum',
                            text: '规格代码'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'productSpecifications',
                            text: '规格参数'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productBzPrice',
                            text: '包装单价'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productPgPrice',
                            text: '抛光单价'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productZgPrice',
                            text: '制管单价'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productWeight',
                            text: '支重'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productYeild',
                            text: '成品率'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productState',
                            text: '生产状态',
                            renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                        		return record.data.productStateText;
		                  	}
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productOrderBy',
                            text: '排序'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 101,
                            dataIndex: 'productNote',
                            text: '备注说明'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            store:'ProductStore',
                            displayInfo: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});