/*
 * File: product/view/ProductWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Product.view.ProductWindow', {
    extend: 'Ext.window.Window',

    id: 'ProductWindow',
    width: 483,
    resizable: false,
    layout: {
        type: 'fit'
    },
    title: '添加产品',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'form',
                            frame: true,
                            id: 'ProductWindowForm',
                            margin: 2,
                            width: 465,
                            bodyPadding: 10,
                            header: false,
                            title: '添加产品',
                            trackResetOnLoad:true,
                            items: [
								{
								    xtype: 'hiddenfield',
								    anchor: '100%',
								    name:'productUuid',
								    fieldLabel: '产品uuid'
								},
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name:'productName',
                                    fieldLabel: '名称'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '规格代码',
                                    name:'productNum',
                                    allowBlank: false,
                                    blankText: '不能为空'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '规格参数',
                                    name:'productSpecifications',
                                    allowBlank: false,
                                    blankText: '不能为空'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    name:'productBzPrice',
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    fieldLabel: '包装单价'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    name:'productPgPrice',
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    fieldLabel: '抛光单价'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    name:'productZgPrice',
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    fieldLabel: '制管单价'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    name:'productWeight',
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    fieldLabel: '支重'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    name:'productYeild',
                                    decimalPrecision: 4,
                                    minValue: 0,
                                    fieldLabel: '成品率'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: '生产状态',
                                    name: 'productState',
                                    id:'productState',
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    editable: false, //启用编辑，主要是为了清空当前的选择项
                                    valueField: 'id',
                                    displayField: 'text',
                                    store:'ProductStateStore',
                                    listeners:{
                                      	afterrender:function(combol){
                            				var firstValue =combol.getStore().data.items[0].data.id;
                            				combol.setValue(firstValue);  
                                      	}
                                	}
                                   
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    name:'productOrderBy',
                                    fieldLabel: '排序'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 55,
                                    name:'productNote',
                                    fieldLabel: '备注说明'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            //height: 40,
                            margin: 2,
                            items: [
                                '->',
                                {
                                    xtype: 'button',
                                    id: 'product_save_btn',
                                    icon: 'img/save.png',
                                    text: '保存'
                                },
                                {
                                    xtype: 'button',
                                    id: 'product_close_btn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});