/*
 * File: workLoadChart/store/BzChartStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WorkLoadChart.store.OrderStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'OrderStore',
            autoLoad:true,
            fields: ['name', 'data'],
            data: [
                   { 'name': '最多',   'data':'DESC' },
                   { 'name': '最少',   'data': 'ASC' }
               ]
        }, cfg)]);
    }
});