/*
 * File: workLoadChart/store/BzChartStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WorkLoadChart.store.TopNumStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TopNumStore',
            autoLoad:true,
            fields: ['name', 'data'],
            data: [
                   { 'name': '5',   'data':'5' },
                   { 'name': '10',   'data': '10' },
                   { 'name': '20',   'data':'20' },
                   { 'name': '30',   'data':'30' },
                   { 'name': '40',   'data':'40' },
                   { 'name': '50',   'data':'50' },
                   { 'name': '60',   'data':'60' },
                   { 'name': '70',   'data':'70' },
                   { 'name': '80',   'data':'80' },
                   { 'name': '90',   'data':'90' },
                   { 'name': '100',   'data':'100' }
               ]
        }, cfg)]);
    }
});