/*
 * File: probationStaff/model/ProbationStaffModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProbationStaff.model.ProbationStaffModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'userUuid'
        },
        {
            name: 'userNumber'
        },
        {
            name: 'userName'
        },
        {
            name: 'userGender'
        },
        {
            name: 'userGenderText'
        },
        {
            name: 'userAge'
        },
        {
            name: 'roleName'
        },
        {
            name: 'roleUuid'
        },
        {
            name: 'pbfDate'
        },
        {
        	name:'userBirthday'
        },
        {
            name: 'pbfLeader'
        },
        {
            name: 'orgUuid'
        },
        {
            name: 'orgName'
        },
        {
        	name:'probationNormalPay'
        },
        {
        	name:'probationMeritPay'
        },
        {
        	name:'probationOtherPay'
        },
        {
        	name:'userNormalPay'
        },
        {
        	name:'userMeritPay'
        },
        {
        	name:'userOtherPay'
        },
        {
        	name:'userNote'
        },
        {
        	name:'idCard'
        }
    ]
});