/*
 * File: bz/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pg.view.MyWindow', {
    extend: 'Ext.window.Window',

    height: 460,
    id: 'BzWindow',
    width: 354,
    layout: {
        type: 'border'
    },
    title: '添加抛光工资',
    modal:true,
    resizable: false,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'center',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            region: 'center',
                            frame: true,
                            margin: 2,
                            layout: {
                                type: 'column'
                            },
                            bodyPadding: 10,
                            header: false,
                            title: '抛光工资',
                            id:'bzFormPanel',
                            trackResetOnLoad:true,
                            items: [
								{
								    xtype: 'hiddenfield',
								    anchor: '100%',
								    fieldLabel: '记录uuid',
								    id: 'loggingUuid',
								    name: 'loggingUuid'
								},
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    margin: 2,
                                    width: 300,
                                    fieldLabel: '日期',
                                    name: 'loggingDate',
                                    id:'loggingDate',
                                    format:'Y-m-d',
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    value:new Date()
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 2 2 2 ',
                                    width: 247,
                                    fieldLabel: '员工工号',
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    id:'loggingUserNumber',
                                    name: 'loggingUserNumber'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '员工号',
                                    id:'loggingUserNumber_hidden'
                                },
                                {
								    xtype: 'hiddenfield',
								    anchor: '100%',
								    fieldLabel: '员工类别',
								    name: 'loggingType',
                                    id:'loggingType',
                                    value:LOGGING_TYPE_PG
								},
                                {
                                    xtype: 'button',
                                    id: 'BzChoseUserBtn',
                                    icon: 'img/search.png',
                                    text: '选择'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 2 2 2 ',
                                    width: 246,
                                    fieldLabel: '产品规格',
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    name: 'loggingProductNum',
                                    id:'loggingProductNum'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '规格代码',
                                    id:'loggingProductNum_hidden'
                                },
                                {
                                    xtype: 'button',
                                    id: 'BzChoseProductBtn',
                                    icon: 'img/search.png',
                                    text: '选择'
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    value:0,
                                    fieldLabel: '抛光单价',
                                	id:'loggingPrice',
                                    name: 'loggingPrice'
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    value:0,
                                    fieldLabel: '支重',
                                    id:'loggingWeight',
                                    name:'loggingWeight'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '员工姓名',
                                    id: 'loggingUserName',
                                    name: 'loggingUserName'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '产品uuid',
                                    id: 'loggingProductUuid',
                                    name: 'loggingProductUuid'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: '员工性别',
                                    id:'loggingUserSex',
                                    name: 'loggingUserSex'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: '员工uuid',
                                    id:'loggingUserUuid',
                                    name: 'loggingUserUuid'
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    decimalPrecision: 2,
                                    minValue: 0,
                                    value:0,
                                    fieldLabel: '数量',
                                    name: 'loggingNumber',
                                    id: 'loggingNumber'
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    value:0,
                                    decimalPrecision: 3,
                                    name: 'loggingAllWeight',
                                    minValue: 0,
                                    id: 'loggingAllWeight',
                                    fieldLabel: '总重'
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    value:1,
                                    decimalPrecision: 0,
                                    name: 'loggingPgNum',
                                    minValue: 0,
                                    id: 'loggingPgNum',
                                    fieldLabel: '抛光次数'
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    allowBlank: false,
                                    blankText: '不能为空',
                                    value:0,
                                    decimalPrecision: 3,
                                    name: 'loggingPgRatio',
                                    minValue: 0,
                                    id: 'loggingPgRatio',
                                    fieldLabel: '抛光比例',
                                    value:LOGGING_PG_NUM_WEIGHT
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    value:0,
                                    fieldLabel: '应得工资',
                                    id: 'loggingWages',
                                    name: 'loggingWages'
                                    	
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    decimalPrecision: 2,
                                    minValue: 0,
                                    value:0,
                                    fieldLabel: '次品数量',
                                    id: 'loggingErrNum',
                                    name: 'loggingErrNum'
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    value:0,
                                    fieldLabel: '次品系数',
                                    id: 'loggingErrRatio',
                                    name: 'loggingErrRatio'
                                    
                                },
                                {
                                    xtype: 'hiddenfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    value:0,
                                    fieldLabel: '应扣工资',
                                    id: 'loggingErrWages',
                                    name: 'loggingErrWages'
                                    
                                },
                                {
                                    xtype: 'numberfield',
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    decimalPrecision: 3,
                                    value:0,
                                    fieldLabel: '实际工资',
                                    id: 'loggingRealityWages',
                                    name: 'loggingRealityWages'
                                },
                                {
                                    xtype: 'textareafield',
                                    height: 53,
                                    margin: '0 2 2 2 ',
                                    width: 300,
                                    fieldLabel: '情况说明',
                                    emptyText: '实际工资=抛光单价*数量*抛光次数(大于1)*抛光比例-(次品数量*次品系数)'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            region: 'south',
                            margin: '0 2 2 2',
                            items: [
                                '->',
                                {
                                    xtype: 'button',
                                    id: 'BzSaveBtn',
                                    icon: 'img/save.png',
                                    text: '保存'
                                },
                                {
                                    xtype: 'button',
                                    id: 'BzCloseBtn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});