/*
 * File: logging/view/ProductWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pg.view.ProductWindow', {
    extend: 'Ext.window.Window',

    height: 511,
    width: 663,
    layout: {
        type: 'fit'
    },
    title: '选择产品规格',
    maximizable: true,
    modal:true,
    id:'ProductWindow',
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'north',
                            margin: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'LoggingProductRefreshBtn',
                                    icon: 'img/reload.png',
                                    text: '刷新'
                                },
                                {
                                    xtype: 'button',
                                    id: 'LoggingProductSureBtn',
                                    icon: 'img/save.png',
                                    text: '确定'
                                },
                                {
                                    xtype: 'button',
                                    id: 'LoggingProductCloseBtn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                },
                                {
                                    xtype: 'button',
                                    id: 'LoggingProductShowSearchBtn',
                                    icon: 'img/search.png',
                                    text: '高级查询'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'north',
                            frame: true,
                            margin: 2,
                            layout: {
                                type: 'column'
                            },
                            bodyPadding: 10,
                            header: true,
                            title: '高级查询',
                            id:'LoggingProductSearchForm',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '规格',
                                    name:'productName',
                                    id:'productName',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '名称',
                                    margin:'0 0 0 10',
                                    name:'productNum',
                                    id:'productNum',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'button',
                                    id: 'LoggingProductSearchBtn',
                                    margin: '0 0  010',
                                    icon: 'img/search.png',
                                    text: '查询'
                                },
                                {
                                    xtype: 'button',
                                    id: 'LoggingProductResetBtn',
                                    margin: '0 0 0 10',
                                    icon: 'img/reset.png',
                                    text: '重置'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            margin: 2,
                            header: false,
                            title: '产品列表',
                            id:'product_gridpanel',
                            store: Ext.create("Pg.store.ProductStore",{autoLoad:true}),
                            columns: [
                                  {
                                      xtype: 'rownumberer',
                                      width: 39,
                                      text: '序号'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      dataIndex: 'productName',
                                      text: '名称'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      dataIndex: 'productNum',
                                      text: '规格代码'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      dataIndex: 'productSpecifications',
                                      text: '规格参数'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      width: 101,
                                      dataIndex: 'productBzPrice',
                                      text: '包装单价'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      width: 101,
                                      dataIndex: 'productPgPrice',
                                      text: '抛光单价'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      width: 101,
                                      dataIndex: 'productZgPrice',
                                      text: '制管单价'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      width: 101,
                                      dataIndex: 'productWeight',
                                      text: '支重'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      width: 101,
                                      dataIndex: 'productState',
                                      text: '生产状态',
                                      renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                                  		return record.data.productStateText;
          		                  	}
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      width: 101,
                                      dataIndex: 'productOrderBy',
                                      text: '排序'
                                  },
                                  {
                                      xtype: 'gridcolumn',
                                      width: 101,
                                      dataIndex: 'productNote',
                                      text: '备注说明'
                                  }
                              ],
                              dockedItems: [
                                  {
                                      xtype: 'pagingtoolbar',
                                      dock: 'bottom',
                                      width: 360,
                                      store:'ProductStore',
                                      displayInfo: true
                                  }
                              ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});