/*
 * File: bz/model/Logging.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Zg.model.Logging', {
    extend: 'Ext.data.Model',

    fields: [
			{
			    name: 'loggingUuid'
			},
			{
			    name: 'loggingDate'
			},
			{
			    name: 'loggingUserUuid'
			},
			{
			    name: 'loggingUserNumber'
			},
			{
			    name: 'loggingUserName'
			},
			{
			    name: 'loggingProductUuid'
			},
			{
			    name: 'loggingProductNum'
			},
			{
			    name: 'loggingNumber'
			},
			{
			    name: 'loggingWeight'
			},
			{
			    name: 'loggingPgNum'
			},
			{
			    name: 'loggingType'
			},
			{
			    name: 'loggingTypeText'
			},
			{
			    name: 'loggingWages'
			},
			{
			    name: 'createUserUuid'
			},
			{
			    name: 'createUserName'
			},
			{
			    name: 'createUserId'
			},
			{
			    name: 'createUserNumber'
			},
			{
			    name: 'note'
			},
			{
			    name: 'createTime'
			},
			{
			    name: 'loggingAllWeight'
			},
			{
			    name: 'loggingPrice'
			},
			{
			    name: 'loggingUserSex'
			},
			{
			    name: 'loggingUserSexText'
			},
			{
				name:'orgName'
			},
			{
				name:'loggingErrNum'
			},
			{
				name:'loggingErrRatio'
			},
			{
				name:'loggingErrWages'
			},
			{
				name:'loggingCheckUserUuid'
			},
			{
				name:'loggingCheckUserName'
			},
			{
				name:'loggingCheckUserNumber'
			},
			{
				name:'loggingRealityWages'
			}
			
			
    ]
});