/*
 * File: yearReport/view/MonthReportWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YearReport.view.MonthReportWindow', {
    extend: 'Ext.window.Window',

    height: 406,
    width: 600,
    layout: {
        type: 'fit'
    },
    title: '明细查询',
    id:'MonthReportWindow',
    modal:true,
    maximizable: true,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'north',
                            margin: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'YearReportDetailReloadBtn',
                                    icon: 'img/reload.png',
                                    text: '刷新'
                                },
                                {
                                    xtype: 'button',
                                    id: 'YearReportDetailExportBtn',
                                    icon: 'img/excel.png',
                                    text: '导出'
                                },
                                {
                                    xtype: 'button',
                                    id: 'YearReportDetailCloseBtn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'YearReportDetailGridPanel',
                            margin: '0  2 2 2',
                            header: false,
                            title: '明细查询',
                            store:Ext.create("YearReport.store.YearDetailReportStore",{autoLoad:true}),
                            columns: [
								{
								    xtype: 'rownumberer',
								    width: 37,
								    text: '序号'
								},
								{
								    xtype: 'gridcolumn',
								    dataIndex: 'loggingDate',
								    text: '月份'
								},
								{
								    xtype: 'gridcolumn',
								    dataIndex: 'orgName',
								    text: '部门'
								},
								{
								    xtype: 'gridcolumn',
								    dataIndex: 'loggingUserName',
								    text: '员工姓名'
								},
								{
								    xtype: 'gridcolumn',
								    dataIndex: 'loggingUserNumber',
								    text: '员工号'
								},
								{
								    xtype: 'gridcolumn',
								    dataIndex: 'loggingUserSex',
								    text: '性别',
								    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
										return record.data.loggingUserSexText;
								  	}
								},
								{
								    xtype: 'gridcolumn',
								    dataIndex: 'loggingType',
								    text: '工作性质',
								    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
										return record.data.loggingTypeText;
								  	}
								},
								{
								    xtype: 'numbercolumn',
								    dataIndex: 'loggingWages',
								    text: '工资',
								    decimalPrecision: 3,
								    summaryType: 'sum'
								},
								{
								    xtype: 'numbercolumn',
								    dataIndex: 'loggingAllWeight',
								    text: '总重',
								    decimalPrecision: 3,
								    summaryType: 'sum'
								}
                            ],
                            features: [
                                       {
                                    	   groupHeaderTpl:  '员工: {name} ({rows.length} 条)',
                                           ftype: 'groupingsummary'
                                       }
                                   ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});