/*
 * File: logging/view/LoggingUserWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tg.view.LoggingUserWindow', {
    extend: 'Ext.window.Window',

    height: 486,
    id: 'LoggingUserWindow',
    width: 647,
    layout: {
        type: 'fit'
    },
    title: '选择员工',
    maximizable: true,
    modal:true,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'north',
                            margin: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'LoggingUserRefreshBtn',
                                    icon: 'img/reload.png',
                                    text: '刷新'
                                },
                                {
                                    xtype: 'button',
                                    id: 'LoggingUserSureBtn',
                                    icon: 'img/save.png',
                                    disable:true,
                                    text: '确定'
                                },
                                {
                                    xtype: 'button',
                                    id: 'LoggingUserCloseBtn',
                                    icon: 'img/close.png',
                                    text: '关闭'
                                }
                            ]
                        },
                        {
                            xtype: 'treepanel',
                            region: 'west',
                            split: true,
                            id: 'OrgTreePanel',
                            margin: '0 0 0 2',
                            width: 200,
                            collapsed: false,
                            collapsible: true,
                            title: '组织机构',
                            store: 'OrgTreeStore',
                            rootVisible: false,
                            viewConfig: {

                            }
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            margin: '0 2 2 0',
                            title: '员工信息列表',
                            id:'LoggingUserGridPanel',
                            store:Ext.create("Tg.store.UserGridPanelStore",{autoLoad:true}),
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 46,
                                    text: '序号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 82,
                                    dataIndex: 'userName',
                                    text: '名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userId',
                                    text: '帐号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userNumber',
                                    text: '员工号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userState',
                                    text: '状态',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                                		return record.data.userStateText;
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userPhone',
                                    text: '办公电话'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userMail',
                                    text: '邮箱'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userMobile',
                                    text: '手机'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userGender',
                                    text: '性别',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                                		return record.data.userGenderText;
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'joinTime',
                                    text: '入职时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userUnversity',
                                    text: '毕业院校'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userDegrees',
                                    hidden:true,
                                    text: '学历',
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                                		return record.data.userDegreesText;
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userAddress',
                                    hidden:true,
                                    text: '籍贯/住址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userBirthday',
                                    text: '生日',
                                    hidden:true,
                                    renderer: function (data, metadata, record, rowIndex, columnIndex, store) {
                                		if(data!='1900-01-01'){
                                			return data;
                                		}
        		                  	}
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userNote',
                                    hidden:true,
                                    text: '备注'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userOrderBy',
                                    hidden:true,
                                    text: '排序'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    store:'UserGridPanelStore',
                                    displayInfo: true
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});